# Generated by Django 6.0.7 on 2026-08-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading of the hero slide', max_length=200)),
                ('subtitle', models.TextField(help_text='Short descriptive paragraph below the title')),
                ('badge_text', models.CharField(default='Official Student Hub', help_text='Badge tag above heading', max_length=100)),
                ('badge_icon', models.CharField(default='fa-graduation-cap', help_text='Font Awesome icon class (e.g. fa-graduation-cap, fa-tags, fa-bolt)', max_length=50)),
                ('theme_color', models.CharField(choices=[('slide-blue', 'Ocean Blue Gradient'), ('slide-green', 'Emerald Green Gradient'), ('slide-purple', 'Royal Purple Gradient')], default='slide-blue', help_text='Slide background gradient theme', max_length=50)),
                ('banner_image', models.ImageField(blank=True, help_text='Optional custom background/hero image', null=True, upload_to='banners/')),
                ('primary_btn_text', models.CharField(default='Explore Store', max_length=100)),
                ('primary_btn_url', models.CharField(default='/products/', max_length=255)),
                ('secondary_btn_text', models.CharField(blank=True, default='Sell an Item', max_length=100, null=True)),
                ('secondary_btn_url', models.CharField(blank=True, default='/admin/products/product/add/', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Slide display order (0 comes first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide this slide on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner Slide',
                'verbose_name_plural': 'Hero Banner Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
