# Generated by Django 6.0.7 on 2026-08-12 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('product_listed', 'New Product Listed'), ('product_sold', 'Product Sold'), ('order_placed', 'Order Placed'), ('order_update', 'Order Status Update'), ('inquiry', 'New Inquiry'), ('message', 'New Message'), ('review', 'New Review'), ('price_drop', 'Price Drop Alert'), ('system', 'System Notification'), ('welcome', 'Welcome')], default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='fa-bell', help_text='FontAwesome icon class', max_length=50)),
                ('link', models.CharField(blank=True, default='', help_text='URL to navigate when clicked', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='The user who triggered this notification (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
