# Generated by Django 6.1 on 2026-08-13 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_pendingproductreview_product_is_approved_and_more'),
        ('sitesetting', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={},
        ),
        migrations.AddField(
            model_name='banner',
            name='featured_product',
            field=models.ForeignKey(blank=True, help_text='Select an existing approved posting from the marketplace to showcase in this banner.', limit_choices_to={'is_approved': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='products.product'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='badge_icon',
            field=models.CharField(blank=True, default='fa-star', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='badge_text',
            field=models.CharField(blank=True, default='Featured Campus Item', max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Optional custom banner image. If empty, uses product photo.', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='primary_btn_text',
            field=models.CharField(blank=True, default='View Listing', max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='primary_btn_url',
            field=models.CharField(blank=True, default='/products/', max_length=255),
        ),
        migrations.AlterField(
            model_name='banner',
            name='secondary_btn_text',
            field=models.CharField(blank=True, default='Explore Store', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='secondary_btn_url',
            field=models.CharField(blank=True, default='/products/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Optional custom description. Leave blank to auto-use product description.'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='theme_color',
            field=models.CharField(choices=[('slide-blue', 'Blue Gradient'), ('slide-green', 'Emerald Green'), ('slide-purple', 'Purple Accent')], default='slide-blue', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, help_text='Optional custom title. Leave blank to auto-use product name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='fa-bell', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(default='system', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
