# Generated by Django 6.1 on 2026-08-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0004_alter_banner_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('data', models.BinaryField()),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Database Stored File',
                'verbose_name_plural': 'Database Stored Files',
            },
        ),
    ]
