# Generated by Django 6.1 on 2026-08-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0005_dbfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DbFile',
        ),
    ]
