# Generated by Django 6.1 on 2026-08-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auction_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProductReview',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Product Review',
                'verbose_name_plural': 'Pending Product Reviews (Moderation Hub)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Designates whether this listing is approved by admin.', verbose_name='Approved by Admin'),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Optional feedback if rejected by admin.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, help_text='Public visibility on store'),
        ),
    ]
